const ENABLE_BOSS_RAID = false;
const MAX_ROOM_PLAYERS = 5;
const RAID_HP_PER_PLAYER = 120000;
const LEADERBOARD_THROTTLE_MS = 400;
const ALLOWED_SCORE_MODES = new Set(['timeAttack']);
const MAX_ACCEPTED_SCORE = Number.MAX_SAFE_INTEGER;
const MAX_ACCEPTED_COMBO = 10000;
const SCORE_VERSION = '1.0.0';
const GAME_SESSION_TTL_MS = 10 * 60 * 1000;
const GAME_SESSION_DURATION_TOLERANCE_MS = 15000;

module.exports = {
  ENABLE_BOSS_RAID,
  MAX_ROOM_PLAYERS,
  RAID_HP_PER_PLAYER,
  LEADERBOARD_THROTTLE_MS,
  ALLOWED_SCORE_MODES,
  MAX_ACCEPTED_SCORE,
  MAX_ACCEPTED_COMBO,
  SCORE_VERSION,
  GAME_SESSION_TTL_MS,
  GAME_SESSION_DURATION_TOLERANCE_MS
};
