const ENABLE_BOSS_RAID = false;
const MAX_ROOM_PLAYERS = 5;
const RAID_HP_PER_PLAYER = 120000;
const LEADERBOARD_THROTTLE_MS = 400;

module.exports = {
  ENABLE_BOSS_RAID,
  MAX_ROOM_PLAYERS,
  RAID_HP_PER_PLAYER,
  LEADERBOARD_THROTTLE_MS
};
